spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/libraryapi
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      # ddl-auto: update

